name: release

on:
  push:
    tags:
      - "v*"

  schedule: 
    - cron: "15 12 * * *" # Avoid peak time.

jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      is_run: ${{ steps.set-is_run.outputs.is_run }}
    steps:
      - uses: actions/checkout@v6
      - name: Check and set is_run
        id: set-is_run
        run: |
          IS_RUN=true
          if [ "${{ github.event_name }}" = "schedule" ]; then
            HEAD=$(git rev-parse HEAD)
            NIGHTLY=$(git ls-remote --tags origin nightly^{} | awk '{print $1}')

            if [ -n "$NIGHTLY" ] && [ "$HEAD" = "$NIGHTLY" ]; then
              IS_RUN=false
            fi
          fi

          echo "is_run=$IS_RUN" >> "$GITHUB_OUTPUT"

  build:
    runs-on: windows-latest
    needs: check-run
    if: needs.check-run.outputs.is_run == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Delete nightly release and tag
        if: github.event_name == 'schedule'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "TAG_NAME=nightly" >> $GITHUB_ENV
          gh release delete nightly --cleanup-tag --yes || echo "No existing nightly"

      - name: Set release tag
        if: github.event_name == 'push'
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $env:GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          tools: 'tools_mingw1310'
          dir: '${{ github.workspace }}'
          cache: 'true'

      - name: Configure
        run: |
          cmake -S . -B build -G "MinGW Makefiles" `
          -DCMAKE_C_COMPILER='${{ github.workspace }}\Qt\Tools\mingw1310_64\bin\gcc.exe' `
          -DCMAKE_CXX_COMPILER='${{ github.workspace }}\Qt\Tools\mingw1310_64\bin\g++.exe' `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\deploy

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Install (deploy)
        run: |
          cmake --install build --config Release

      - name: Compress install folder
        run: |
          Compress-Archive -Path ${{ github.workspace }}\deploy\* -DestinationPath SolTranslator.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ github.event_name == 'schedule' && 'nightly' || format('SolTranslator {0}', env.TAG_NAME) }}
          prerelease: ${{ github.event_name == 'schedule' }}
          target_commitish: ${{ github.sha }}
          files: SolTranslator.zip
