name: release

on:
  push:
    tags:
      - "v*"

  schedule:
    - cron: "50 5 * * *"  # UTC 00:00

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set nightly tag
        if: github.event_name == 'schedule'
        run: |
          echo "TAG_NAME=nightly-$(Get-Date -Format yyyyMMdd)" >> $env:GITHUB_ENV

      - name: Set release tag
        if: github.event_name == 'push'
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $env:GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          tools: 'tools_mingw1310'
          dir: '${{ github.workspace }}'
          cache: 'true'

      - name: Configure
        run: |
          cmake -S . -B build -G "MinGW Makefiles" `
          -DCMAKE_C_COMPILER='${{ github.workspace }}\Qt\Tools\mingw1310_64\bin\gcc.exe' `
          -DCMAKE_CXX_COMPILER='${{ github.workspace }}\Qt\Tools\mingw1310_64\bin\g++.exe' `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\deploy

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Install (deploy)
        run: |
          cmake --install build --config Release

      - name: Compress install folder
        run: |
          Compress-Archive -Path ${{ github.workspace }}\deploy\* -DestinationPath SolTranslator.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          prerelease: ${{ github.event_name == 'schedule' }}
          files: SolTranslator.zip
