name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  schedule: 
    - cron: "13 23 * * *"

jobs:
  check-run-build:
    runs-on: ubuntu-slim
    outputs:
      run-build: ${{ steps.set-run-build.outputs.run-build }}
    steps:
      - uses: actions/checkout@v6
      - name: Check run-build
        id: set-run-build
        run: |
          IS_RUN=true
          if [ "${{ github.event_name }}" = "schedule" ]; then
            HEAD=$(git rev-parse HEAD)
            NIGHTLY=$(git ls-remote --tags origin nightly^{} | awk '{print $1}')

            if [ -n "$NIGHTLY" ] && [ "$HEAD" = "$NIGHTLY" ]; then
              IS_RUN=false
              echo "::notice::No new commit. Terminate the nightly build."
            fi
          fi

          echo "run-build=$IS_RUN" >> "$GITHUB_OUTPUT"

  build:
    runs-on: windows-latest
    needs: check-run-build
    if: needs.check-run-build.outputs.run-build == 'true'

    env:
      TAG_NAME: |-
        ${{ case(
          github.event_name == 'schedule', 'nightly',
          github.event_name == 'push' && github.ref_type == 'branch', 'continuous',
          github.ref_name
        ) }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
#          version: '6.11.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'extensions.qtpdf.6101.win64_msvc2022_64'
          dir: '${{ github.workspace }}'
          cache: 'true'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/deploy

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Install (deploy)
        run: |
          cmake --install build --config Release

      - name: Compress install folder
        run: |
          Compress-Archive -Path ${{ github.workspace }}/deploy/* -DestinationPath SolTranslator.zip


      - name: Delete nightly release and tag
        if: github.event_name == 'schedule'
        continue-on-error: true
        run: |
          gh release delete nightly --yes --repo $env:GITHUB_REPOSITORY || echo "No release or draft found"
          git push origin --delete nightly || echo "Tag does not exist"


      - name: Delete continuous release and tag
        if: github.event_name == 'push' && github.ref_type == 'branch'
        continue-on-error: true
        run: |
          gh release delete continuous --yes --repo $env:GITHUB_REPOSITORY || echo "No release or draft found"
          git push origin --delete continuous || echo "Tag does not exist"


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          name: |-
            ${{ case(
              github.event_name == 'schedule', 'nightly',
              github.event_name == 'push' && github.ref_type == 'branch', 'continuous',
              format('SolTranslator {0}', env.TAG_NAME)
            ) }}
          prerelease: ${{ github.event_name == 'schedule' || (github.event_name == 'push' && github.ref_type == 'branch') }}
          files: SolTranslator.zip
